# Generated by Django 2.1.5 on 2019-02-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('netTimeRatio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('netSpeedAverage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
