# Generated by Django 2.1.5 on 2019-02-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drives',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='driving',
            field=models.BooleanField(default=False),
        ),
    ]
