# Generated by Django 2.1.5 on 2019-02-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190224_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distTraveled', models.IntegerField()),
                ('eyeRatio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('timeSpent', models.IntegerField()),
                ('idVal', models.IntegerField()),
                ('userTag', models.CharField(max_length=30)),
            ],
        ),
    ]
