# Generated by Django 2.1.5 on 2019-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='netTimeRatio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
