# Generated by Django 2.1.5 on 2019-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190224_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('dataPoint', models.IntegerField()),
                ('drNumber', models.IntegerField()),
                ('eyeRatio', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dataPoint',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
